// v12.31.0(P3):宣传片/预告片促销模板(在文件末尾 spread 进 storyTemplates;promo-template 只 import 本文件的类型,无运行时环依赖)。
import { PROMO_TEMPLATES } from './promo-template';

export interface StoryTemplate {
  id: string;
  name: string;           // Chinese name
  nameEn: string;         // English name
  icon: string;           // Emoji icon
  category: string;       // Genre category
  description: string;    // Short description
  exampleIdea: string;    // Example story idea to pre-fill
  structureHint: string;  // Structure guidance for the AI writer
  emotionCurve: string;   // Emotion curve pattern description
  keyElements: string[];  // Key story elements
  styleRecommendation: string; // Recommended visual style
  shotCount: { min: number; max: number }; // Suggested shot range
  colorPalette: string;   // Suggested color keywords
  // v2.18: 模板检索 / 自动表单填充用的扩展字段 (旧模板有, 新模板必须)
  /** 标签 — 给筛选 / 推荐用. 如 ['短剧', '热血', '动漫风'] */
  tags?: string[];
  /** 推荐单镜时长 (秒) — 给 create 页 duration 选择器自动填 */
  recommendedDuration?: 5 | 6 | 10 | 15;
  /** 推荐画幅 — 给 create 页 aspect 自动填 */
  recommendedAspect?: '16:9' | '9:16' | '1:1' | '2.35:1';
  /** 推荐 cameraDefault id (CAMERA_LANGUAGE_PRESETS 之一) — 一键带运镜 */
  recommendedCamera?: 'push-in' | 'pull-out' | 'orbit' | 'dolly-zoom' | 'whip-pan'
    | 'crash-zoom' | 'handheld' | 'locked-tripod' | 'crane-up' | 'tilt-down' | 'tracking' | 'arc';
}

export const storyTemplates: StoryTemplate[] = [
  {
    id: 'power-fantasy',
    name: '爽文逆袭',
    nameEn: 'Power Fantasy',
    icon: '⚡',
    category: '热血爽文',
    description: '弱者崛起，一路打脸反杀',
    exampleIdea: '被所有人嘲笑的废物少年，在绝望中觉醒了被封印千年的神级天赋，从此踏上一路打脸、复仇、登顶的爽快征程，誓要让所有轻视他的人后悔',
    structureHint: '第一幕：展示主角遭受屈辱和打压的悲惨处境，强烈对比弱者与强者的差距，激发共鸣；第二幕：主角意外觉醒或得到机遇，开始快速成长，连续反杀曾经的敌人，每次胜利都要有"打脸"的爽感；第三幕：面对终极反派，主角展现全部实力，完成最终逆袭，赢得尊重与荣耀。节奏要快，爽点要密集，至少每幕有一个高潮打脸场景。',
    emotionCurve: '低谷→屈辱→觉醒→爽感爆发→高潮逆袭',
    keyElements: ['屈辱开局', '天赋觉醒', '连续反杀', '实力碾压', '荣耀登顶'],
    styleRecommendation: 'Anime 3D',
    shotCount: { min: 6, max: 10 },
    colorPalette: 'golden power aura, dramatic lightning, vibrant contrast',
  },
  {
    id: 'sweet-romance',
    name: '甜宠恋爱',
    nameEn: 'Sweet Romance',
    icon: '🌸',
    category: '甜宠爱情',
    description: '甜蜜互动，心动瞬间',
    exampleIdea: '冷漠高冷的霸道总裁与阳光活泼的普通女孩意外相遇，从最初的针锋相对到渐渐心动，经历误会与考验，最终在樱花飘落的夜晚相拥告白，甜到窒息',
    structureHint: '第一幕：男女主角相遇，性格截然相反制造火花，展示各自特点和背景，埋下感情线；第二幕：一系列甜蜜日常互动，误会与解释交替出现，情感逐渐升温，设置至少两个心动的名场面；第三幕：遭遇外部考验或误会危机，经历短暂分离后，在特别场合（如雨中、樱花树下）深情表白，甜蜜收场。全程要保持甜蜜基调，心动感要溢出屏幕。',
    emotionCurve: '相遇火花→甜蜜互动→心动升温→危机考验→幸福告白',
    keyElements: ['命运相遇', '性格反差', '甜蜜日常', '心动名场面', '深情告白'],
    styleRecommendation: 'Ghibli',
    shotCount: { min: 5, max: 8 },
    colorPalette: 'soft pink, warm golden light, pastel bloom, romantic haze',
  },
  {
    id: 'mystery-thriller',
    name: '悬疑推理',
    nameEn: 'Mystery Thriller',
    icon: '🔍',
    category: '悬疑推理',
    description: '层层剥茧，真相震惊',
    exampleIdea: '知名侦探收到一封匿名信，指引他来到一座与世隔绝的庄园，七个嘉宾中隐藏着一位连环杀手，随着一具具尸体出现，侦探逐渐发现每个人都有致命秘密，而真凶竟是他最信任的人',
    structureHint: '第一幕：以强烈悬念开场（发现尸体/神秘事件），介绍所有嫌疑人并为每人埋下可疑线索，营造压抑紧张氛围；第二幕：侦探逐一排查，每次调查都有新发现，但也出现新的疑问和反转，证据指向不同方向；第三幕：真正的线索在看似无关紧要的细节中，最终大推理揭示真相，结尾要有震撼的反转或令人深思的结局。保持悬念，每幕都要有新的谜题。',
    emotionCurve: '悬念导入→紧张调查→误导迷惑→真相逼近→震撼揭秘',
    keyElements: ['神秘案件', '错综线索', '多重疑点', '关键反转', '真相揭露'],
    styleRecommendation: 'Neo Noir',
    shotCount: { min: 6, max: 10 },
    colorPalette: 'dark shadows, cold blue, spotlight contrast, foggy noir',
  },
  {
    id: 'xianxia-fantasy',
    name: '古风仙侠',
    nameEn: 'Xianxia Fantasy',
    icon: '🐉',
    category: '仙侠玄幻',
    description: '修炼成仙，斩妖除魔',
    exampleIdea: '天资平平的凡人少年，机缘巧合得到上古仙人传承，踏上修仙之路，在九州大地斩妖伏魔，历经九死一生的磨难，终于渡劫飞升，成为保护苍生的一代剑仙',
    structureHint: '第一幕：展示凡人世界的格局和主角平凡出身，一场奇遇（得宝/拜师/机缘）开启修仙之路，描绘仙侠世界的宏大设定和等级体系；第二幕：修炼过程中遭遇强敌和魔道势力，一次惨败或至亲遇难成为突破契机，展示仙法对决的壮观场面；第三幕：终极大战，法术齐出，以恢弘的仙法对决收尾，展现飞升成仙的壮丽画面，意境悠远。注重水墨仙侠的视觉美感。',
    emotionCurve: '凡尘起始→机缘觉醒→磨难历练→突破蜕变→飞升成仙',
    keyElements: ['仙缘机遇', '修炼突破', '妖魔对决', '法宝神器', '飞升成道'],
    styleRecommendation: 'Ink Wash',
    shotCount: { min: 6, max: 12 },
    colorPalette: 'ethereal jade, golden immortal glow, ink wash mountains, celestial mist',
  },
  {
    id: 'cyberpunk',
    name: '赛博朋克',
    nameEn: 'Cyberpunk',
    icon: '🤖',
    category: '科幻赛博',
    description: '霓虹都市，反抗机器',
    exampleIdea: '2177年的新上海，被大公司废弃的增强人类黑客决定入侵宰制全城的超级AI系统，在霓虹闪烁的底层街道穿梭，揭开人类与机器共存的残酷真相，最终在赛博空间发动最后的反叛',
    structureHint: '第一幕：沉浸式展示赛博朋克世界观——阶级分化的未来都市、霓虹霓虹的底层与精英阶层的鲜明对比，主角在压迫性的社会结构中接受任务；第二幕：入侵行动逐步升级，在数字空间与现实空间之间穿梭，遭遇公司打手和AI守卫的追杀，队友牺牲或背叛增加戏剧张力；第三幕：最终对决在赛博空间进行，视觉上要呈现数字与现实交融的奇观，结局留有反思——科技进步究竟是解放还是枷锁。',
    emotionCurve: '压抑现实→激活反抗→危机升级→赛博决战→深刻反思',
    keyElements: ['反乌托邦', '赛博增强', '黑客入侵', '公司霸权', 'AI觉醒'],
    styleRecommendation: 'Cyber Neon',
    shotCount: { min: 6, max: 10 },
    colorPalette: 'neon cyan magenta, rain-soaked streets, holographic data, electric blue',
  },
  {
    id: 'post-apocalyptic',
    name: '末日废土',
    nameEn: 'Post-Apocalyptic',
    icon: '☢️',
    category: '末日生存',
    description: '废土求生，重建希望',
    exampleIdea: '核战争后三十年的废土大陆，孤独的废土侦察兵在辐射荒漠中意外发现一个幸存儿童，两人踏上寻找传说中未受污染净土的旅程，途中结识形形色色的幸存者，在互相扶持中重燃人类文明的希望之火',
    structureHint: '第一幕：极具冲击力的末日世界展示——焦土与废墟、变异生物、资源匮乏的生存困境，主角的日常求生展现废土法则；第二幕：旅程中遭遇废土帮派、变异生物和道德两难，每一次选择都影响生存与信念，并逐渐揭示末日前文明的碎片；第三幕：抵达目的地面临终极考验，希望与绝望交织，结局要给出对人类本性和文明意义的回答，可喜可悲但必须有力量。',
    emotionCurve: '绝望废土→求生挣扎→旅途磨砺→信念考验→希望重燃',
    keyElements: ['废土求生', '末日景象', '道德抉择', '互助情谊', '文明重建'],
    styleRecommendation: 'Cinematic',
    shotCount: { min: 6, max: 10 },
    colorPalette: 'dusty orange, ash grey, burning amber, desolate wasteland',
  },
  {
    id: 'campus-youth',
    name: '校园青春',
    nameEn: 'Campus Youth',
    icon: '🎓',
    category: '青春校园',
    description: '青葱岁月，纯真情谊',
    exampleIdea: '高中最后一年，原本成绩垫底的转学生意外成为学校乐队的主唱，在与死对头同学的磨合中逐渐建立深厚友情，他们共同为毕业演出拼尽全力，在舞台上绽放最美的青春',
    structureHint: '第一幕：活泼展示校园环境和主角群体，设置青春特有的烦恼和梦想——学业压力、友情考验、朦胧情感，轻松基调中埋下成长主题；第二幕：围绕共同目标（比赛/演出/毕业）展开，友情破裂与修复、青春期的误解与和解，展示每个人独特的闪光点；第三幕：关键时刻的全力以赴，团结一致的高潮场面，毕业季的感伤与感恩，让青春的美好与遗憾都得到完美表达。',
    emotionCurve: '轻松日常→矛盾冲突→成长蜕变→齐心协力→青春永恒',
    keyElements: ['纯真友情', '青春梦想', '成长烦恼', '热血拼搏', '毕业告别'],
    styleRecommendation: 'Ghibli',
    shotCount: { min: 5, max: 8 },
    colorPalette: 'warm sunlight, cherry blossom pink, vibrant youth energy, nostalgic golden',
  },
  {
    id: 'palace-intrigue',
    name: '宫斗权谋',
    nameEn: 'Palace Intrigue',
    icon: '👑',
    category: '宫廷权谋',
    description: '深宫算计，权力游戏',
    exampleIdea: '出身书香门第的才女进入皇宫，面对步步为营的妃嫔陷害和错综复杂的政治派系，她隐忍蛰伏、运筹帷幄，以过人的才智逐一化解危机，最终在权力棋局中从棋子变为执棋之人',
    structureHint: '第一幕：宏大的皇宫设定与森严等级制度展示，主角进宫初期的天真与不适，初遭算计，暗示宫廷险恶；第二幕：主角在多次危机中从被动到主动，学会以其人之道还治其人之身，展示精彩的心理博弈和阵营角力，每一计谋都有铺垫和破解；第三幕：终极权力角逐，主角将所有棋局收于掌中，以一个令人拍案叫绝的谋略完成终极逆转，展示权谋之美与人性的复杂。',
    emotionCurve: '入宫懵懂→遭算计→蛰伏学习→反客为主→权谋登顶',
    keyElements: ['权力博弈', '心机算计', '阵营角力', '借力打力', '一步棋局'],
    styleRecommendation: 'Anime 3D',
    shotCount: { min: 6, max: 10 },
    colorPalette: 'imperial gold, deep crimson, jade green, opulent palace grandeur',
  },
  {
    id: 'urban-fantasy',
    name: '都市奇幻',
    nameEn: 'Urban Fantasy',
    icon: '🌆',
    category: '都市奇幻',
    description: '现代都市，异能觉醒',
    exampleIdea: '平凡上班族在地铁意外接触神秘符文后，发现自己能看见隐藏在城市中的妖魔鬼怪，被卷入人类世界与灵异界之间的秘密战争，用普通人的智慧和意外得来的奇特力量守护这座城市的平衡',
    structureHint: '第一幕：从完全正常的都市日常切入，主角的异能觉醒要自然合理，展示现实世界背后的奇幻层叠——街角的妖怪、地铁中的灵体，惊奇感与亲切感并存；第二幕：主角学习并适应新世界规则，结识奇幻世界的伙伴与敌人，人类世界与灵异世界的矛盾升级，普通人的视角带来独特洞察；第三幕：两界冲突的高峰，主角用"常识"和人情味破解看似无解的危机，强调人性温度，结局要有对两种世界共存的温暖展望。',
    emotionCurve: '日常平凡→异能觉醒→两界适应→危机升级→智慧守护',
    keyElements: ['异能觉醒', '双重世界', '灵异存在', '都市冒险', '人性温度'],
    styleRecommendation: 'Dreamwave',
    shotCount: { min: 5, max: 9 },
    colorPalette: 'urban neon overlay, mystical purple, reality-magic blend, twilight city',
  },
  {
    id: 'wuxia-martial',
    name: '武侠江湖',
    nameEn: 'Wuxia Martial Arts',
    icon: '⚔️',
    category: '武侠热血',
    description: '快意恩仇，江湖儿女',
    exampleIdea: '少年侠客在师门被灭门仇人所毁后，带着父亲遗留的残缺剑谱踏入江湖，在纷乱的武林格局中磨砺武学、结交豪侠，历经十年追凶之路，终于在血与剑中完成复仇，领悟武道真谛',
    structureHint: '第一幕：江湖世界宏观展示——帮派林立、武林格局，主角背景与仇恨起源，少年意气的出发，武功起步阶段展现成长空间；第二幕：闯荡江湖过程中结识挚友和劲敌，多次武斗展示功夫成长，遭遇江湖规则的残酷，义气与利益的抉择；第三幕：终极对决前的蜕变与顿悟，最后的对决要有武学层面的精彩展现，结局超越复仇本身——达到对武道和侠义精神的升华。',
    emotionCurve: '血海深仇→踏入江湖→磨砺成长→义气豪情→顿悟超脱',
    keyElements: ['侠义精神', '武功精进', '江湖恩怨', '豪侠情谊', '武道顿悟'],
    styleRecommendation: 'Poetic Mist',
    shotCount: { min: 6, max: 10 },
    colorPalette: 'misty mountains, bamboo green, sword gleam silver, ancient amber',
  },
  {
    id: 'slice-of-life',
    name: '治愈日常',
    nameEn: 'Slice of Life',
    icon: '☕',
    category: '治愈温情',
    description: '平淡温暖，治愈人心',
    exampleIdea: '城市角落一家不起眼的小书店，老店主和每天光顾的形形色色客人——迷茫的年轻人、孤独的老者、失恋的女孩——在书香氤氲中互相倾诉，用一本书、一杯茶、一段对话，找到继续前行的力量',
    structureHint: '第一幕：用细腻的笔触展示日常环境的温馨细节，引入主要人物，以轻描淡写的方式勾勒各人的生活困境或内心渴望；第二幕：几个平行的小故事在同一空间交织，展现人与人之间偶然却珍贵的连接，用生活中真实细小的瞬间触动情感；第三幕：不需要大起伏，但要有情感的到达——一个感悟、一次释怀、一种温柔的和解。让观众感受到生活平凡却值得珍惜，以静谧美好收尾。',
    emotionCurve: '平静日常→细腻感受→情感积累→温柔触动→治愈升华',
    keyElements: ['日常温情', '人物群像', '生活细节', '偶然连接', '内心治愈'],
    styleRecommendation: 'Ghibli',
    shotCount: { min: 4, max: 7 },
    colorPalette: 'warm amber, soft morning light, cozy interior, gentle pastels',
  },
  {
    id: 'horror-thriller',
    name: '恐怖惊悚',
    nameEn: 'Horror',
    icon: '👻',
    category: '恐怖惊悚',
    description: '惊悚反转，毛骨悚然',
    exampleIdea: '深夜独居的女作家在写作时发现电脑屏幕上的文字自动变化，描述的正是当下发生在她身上的事，当她意识到自己正在被某个存在"书写"时，试图逃脱却发现整个故事都已布局完毕',
    structureHint: '第一幕：营造正常氛围后植入第一个令人不安的细节，让观众和主角同时感到"哪里不对"，慢慢建立恐惧感而非立即揭晓恐惧来源；第二幕：恐惧逐渐升级，主角的行动反而推进诡异的发展，多设置"以为逃脱却发现更深陷其中"的绝望感，心理恐惧要强于视觉恐惧；第三幕：揭晓真相或保留模糊的反转——可以是心理扭曲的解释，也可以是无法解释的超自然，结局要给观众留下强烈的情绪震荡和反复回味的细思极恐。',
    emotionCurve: '不安预感→恐惧积累→绝望升级→极度惊悚→细思极恐',
    keyElements: ['不安氛围', '心理恐惧', '绝望陷阱', '惊悚反转', '细思极恐'],
    styleRecommendation: 'Neo Noir',
    shotCount: { min: 5, max: 8 },
    colorPalette: 'deep shadow black, sickly green, blood red, unsettling darkness',
  },
  // ── v2.18: 6 个新增模板, 覆盖此前缺失的题材 ──
  {
    id: 'sci-fi-space',
    name: '科幻太空',
    nameEn: 'Space Opera',
    icon: '🚀',
    category: '科幻太空',
    description: '星际探索，宇宙史诗',
    exampleIdea: '一支被流放到银河系边缘的勘探小队意外发现了一个被遗忘的古老文明遗迹,激活的全息信号揭示了全宇宙正面临一场即将到来的"大寂静",而拯救的钥匙握在一位早已消失的女科学家手中',
    structureHint: '第一幕:展示星际飞船中孤独的日常 + 突然的发现,用宏大太空镜头建立"小人物对宇宙"的张力;第二幕:每个新发现都伴随未知威胁,角色之间因恐惧产生分歧,船员决断的代价不断升级;第三幕:在巨大牺牲下激活遗迹关键,留下"寂静与回响"式开放结局,致敬 2001 太空漫游 / 星际穿越的克制美学。多用大对比镜头(渺小人物 vs 壮观星云)。',
    emotionCurve: '孤独探索→发现震撼→未知恐惧→关键牺牲→宇宙启示',
    keyElements: ['星际飞船', '远古遗迹', '团队分歧', '宇宙级威胁', '开放结局'],
    styleRecommendation: 'Cinematic',
    shotCount: { min: 6, max: 10 },
    colorPalette: 'deep space indigo, nebula magenta, sterile white interiors, holographic cyan',
    tags: ['科幻', '宏大叙事', '团队戏', '硬科幻'],
    recommendedDuration: 10,
    recommendedAspect: '2.35:1',
    recommendedCamera: 'crane-up',
  },
  {
    id: 'kids-cartoon',
    name: '儿童动画',
    nameEn: 'Kids Cartoon',
    icon: '🐰',
    category: '儿童亲子',
    description: '温暖友谊,简单快乐',
    exampleIdea: '森林里害羞的小兔子小棉一直不敢和别人玩,直到遇到了热情的小狐狸阿橙,两个看似不同的小朋友在一次寻找彩虹蘑菇的冒险中,学会了什么是真正的朋友,也帮助森林里的其他动物找回了快乐',
    structureHint: '第一幕:用明亮温柔色调展示小棉的孤单 + 阿橙的活泼,两个角色第一次相遇要可爱有记忆点;第二幕:冒险中遇到 2-3 个小困难(过小溪/找路/帮助迷路的小松鼠),每个困难都体现"友谊的力量"主题,语言简单情节直接;第三幕:找到彩虹蘑菇但更重要的是分享给所有动物朋友,大团圆收尾,要有一句简单的核心台词("最棒的不是找到蘑菇,是一起寻找的人")。全程禁止暴力 / 死亡 / 阴暗主题, 适合 3-8 岁观众。',
    emotionCurve: '温暖介绍→可爱相遇→冒险互助→温情高潮→大团圆',
    keyElements: ['萌系角色', '森林冒险', '友谊主题', '互助情节', '温馨大结局'],
    styleRecommendation: 'Ghibli',
    shotCount: { min: 5, max: 7 },
    colorPalette: 'pastel rainbow, soft mint green, sunny yellow, gentle storybook palette',
    tags: ['儿童', '亲子', '温馨', '动物', '友谊'],
    recommendedDuration: 5,
    recommendedAspect: '16:9',
    recommendedCamera: 'tracking',
  },
  {
    id: 'historical-biopic',
    name: '历史人物',
    nameEn: 'Historical Biopic',
    icon: '📜',
    category: '历史传记',
    description: '一段历史,一个人物',
    exampleIdea: '北宋年间一位寒门书生,在父亲含冤入狱后毅然弃文从武,历经十年戍边塞外,从一名小卒成长为镇守一方的将军,最终在收复失地的最后一战中,为给父亲洗清污名而亲自冲锋陷阵',
    structureHint: '第一幕:用风土人情镜头交代时代背景 + 主角原本的安稳生活,父亲蒙冤事件作为激励事件要有足够冲击;第二幕:展现"成长"的多个段落 — 入伍受辱 / 艰苦训练 / 第一次实战 / 升迁挫折,每个转折都要有真实的历史细节(兵器/服饰/话语);第三幕:收复失地的关键战役,主角的私人复仇与家国大义合二为一,结局可以悲壮也可以荣耀,但必须留下时代印记。注意尊重史实,不戏说。',
    emotionCurve: '安稳→变故→隐忍→成长→悲壮高潮',
    keyElements: ['时代背景', '蒙冤激励', '从军成长', '历史细节', '家国情怀'],
    styleRecommendation: 'Cinematic',
    shotCount: { min: 6, max: 10 },
    colorPalette: 'aged ink, sepia gold, banner red, weathered earth tones',
    tags: ['历史', '严肃', '战争戏', '人物弧光'],
    recommendedDuration: 10,
    recommendedAspect: '2.35:1',
    recommendedCamera: 'tracking',
  },
  {
    id: 'animal-fable',
    name: '动物寓言',
    nameEn: 'Animal Fable',
    icon: '🦊',
    category: '寓言哲思',
    description: '拟人动物,深刻寓意',
    exampleIdea: '森林深处的一群动物突然发现山泉的水开始变浑,聪明的狐狸坚持寻找根源却被多数动物嘲笑"没事找事",直到山下村民开始大规模生病,动物们才意识到上游的某座工厂在偷排,这场寻找真相的旅程最终成为了对盲从与勇气的寓言',
    structureHint: '第一幕:用拟人化镜头展示动物社群的"日常政治",主角(通常是少数派)的不同被强调;第二幕:主角追查被孤立 → 发现初步线索却被否定 → 危机加深证明主角是对的,这个"被嘲笑的清醒者"弧线必须扎实;第三幕:真相揭露往往涉及人类活动的隐喻(环保/官僚/盲从),寓言式结尾留下让观众思考的台词("我们看到了水,却看不到污染"),不要把道理说穿。',
    emotionCurve: '日常→质疑→孤立→危机→寓意揭示',
    keyElements: ['拟人动物', '少数派主角', '盲从对照', '环境隐喻', '寓言收束'],
    styleRecommendation: 'Anime 3D',
    shotCount: { min: 5, max: 8 },
    colorPalette: 'forest emerald, fading autumn ochre, polluted gray-green tint',
    tags: ['寓言', '哲思', '环保', '社会议题', '老少咸宜'],
    recommendedDuration: 6,
    recommendedAspect: '16:9',
    recommendedCamera: 'arc',
  },
  {
    id: 'food-vlog',
    name: '美食 vlog',
    nameEn: 'Food Vlog',
    icon: '🍜',
    category: '美食生活',
    description: '一道菜,一段故事',
    exampleIdea: '一位在大城市工作压力很大的年轻人,周末回到老家的乡下,跟着外婆学做一道她小时候最爱的红烧肉,从买菜 / 切配 / 慢炖 / 上桌的全过程中,慢慢理解了"家的味道"为什么是任何米其林都替代不了的',
    structureHint: '第一幕:大城市快节奏 / 焦虑的对比镜头 → 决定回乡 → 抵达老家的"慢"瞬间(炊烟/灶台/外婆的笑);第二幕:做菜过程要详细到每一步 — 选肉 / 焯水 / 炒糖色 / 慢炖 / 收汁,每一步穿插一段外婆的回忆或主角小时候的闪回,把菜的工艺与情感绑死;第三幕:全家围坐吃饭,主角第一口的反应,简短的对话或独白点出"家的味道"主题,结尾留一个空盘子的特写。镜头多用近景特写 + 暖光,声音设计很重要(切菜声/油爆声/低语)。',
    emotionCurve: '都市焦虑→归乡放松→工艺沉浸→情感涌现→温暖余韵',
    keyElements: ['食材特写', '工艺过程', '回忆闪回', '家人对话', '空盘留白'],
    styleRecommendation: 'Ghibli',
    shotCount: { min: 6, max: 8 },
    colorPalette: 'warm kitchen amber, steam haze, soy-glaze caramel, soft window daylight',
    tags: ['美食', '治愈', '家庭', '乡村', '慢节奏'],
    recommendedDuration: 6,
    recommendedAspect: '16:9',
    recommendedCamera: 'push-in',
  },
  {
    id: 'music-video',
    name: '音乐 MV',
    nameEn: 'Music Video',
    icon: '🎵',
    category: '音乐 MV',
    description: '画面跟着情绪走',
    exampleIdea: '一首关于"出走"的轻摇滚单曲,画面跟随一个戴耳机的年轻人在夜晚的城市里漫无目的地走 / 跑 / 等地铁,随着歌词从迷茫 → 释怀 → 决断,画面色调与节奏不断变化,最终在天亮的瞬间他看向镜头微笑',
    structureHint: '第一幕:第一段歌词对应"困住"的画面(密集人群/红绿灯/重复 motif),色调偏冷蓝,节奏切得相对慢;第二幕:副歌进入,画面开始大量运动镜头(奔跑/跳跃/街道流光),色调升温到琥珀,剪辑节奏与鼓点对齐,加入慢动作高光;第三幕:bridge → 末段副歌,画面回归宁静但色调温暖,主角的状态变化必须可见(姿态/眼神),最终镜头与歌词的最后一拍精准对位。MV 的核心是"视听节奏耦合",不强求叙事完整。',
    emotionCurve: '困住→挣扎→突破→释放→坦然',
    keyElements: ['节奏剪辑', '色调演进', '运动镜头', '视听对位', '终镜回望'],
    styleRecommendation: 'Cinematic',
    shotCount: { min: 8, max: 12 },
    colorPalette: 'neon city blue, amber street lamp, dawn rose, music video saturated palette',
    tags: ['音乐', 'MV', '风格化', '城市', '青年'],
    recommendedDuration: 5,
    recommendedAspect: '16:9',
    recommendedCamera: 'whip-pan',
  },
  ...PROMO_TEMPLATES, // v12.31.0(P3):宣传片/预告片模板,复用现有管线生成
];

export function getTemplateById(id: string): StoryTemplate | undefined {
  return storyTemplates.find(t => t.id === id);
}
